---
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/wcr/joint/BL_propeller_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ